title: Alexis Aubry
owner: Alexis Aubry
email: me@alexaubry.fr
copright_years: "2017 - 2018"

description: >-
  Hey, I'm Alexis! I'm a French law student and software engineer.
  I build apps for Apple platforms and work on open source projects.

url: "https://alexaubry.fr"
twitter_username: _alexaubry
github_username:  alexaubry

markdown: kramdown

tabs:
  - title: "About"
    path: "/"
  - title: "Projects"
    path: "/projects"
  - title: "Contact Me"
    path: "/contact"

ga-id: "UA-106457303-2"
available_for_hire: true
hiring_location: "Berlin or remotely"