title: Alexis Aubry
owner: Alexis Aubry
email: me@alexaubry.fr
copright_years: "2017 &ndash; 2019"
url: "https://alexaubry.fr"

description: >-
  Hey, I'm Alexis! I'm a French software engineer living in Berlin.
  I build apps for Apple platforms and work on open source projects.

twitter_username: _alexaubry
github_username:  alexaubry

markdown: kramdown

tabs:
  - title: "About"
    path: "/"
  - title: "Work"
    path: "/work"
  - title: "Contact"
    path: "/contact"

available_for_hire: false
hiring_location: "Berlin or remotely"

plugins:
  - jekyll-sitemap